USE [master]
GO

/****** Object:  Database [LostandFound]    Script Date: 11/10/2020 12:54:42 PM ******/
CREATE DATABASE [LostandFound]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LostandFound_data', FILENAME = N'F:\sqldata\LostandFound\LostandFound.mdf' , SIZE = 228800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'LostandFound_log', FILENAME = N'E:\sqllog\LostandFound\LostandFound.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LostandFound] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LostandFound].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LostandFound] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LostandFound] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LostandFound] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LostandFound] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LostandFound] SET ARITHABORT OFF 
GO

ALTER DATABASE [LostandFound] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LostandFound] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [LostandFound] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LostandFound] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LostandFound] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LostandFound] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LostandFound] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LostandFound] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LostandFound] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LostandFound] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LostandFound] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LostandFound] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LostandFound] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [LostandFound] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LostandFound] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LostandFound] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LostandFound] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LostandFound] SET RECOVERY FULL 
GO

ALTER DATABASE [LostandFound] SET  MULTI_USER 
GO

ALTER DATABASE [LostandFound] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [LostandFound] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LostandFound] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LostandFound] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LostandFound] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LostandFound] SET QUERY_STORE = OFF
GO

USE [LostandFound]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [LostandFound] SET  READ_WRITE 
GO

